services:
  # Backend API Service
  - type: web
    name: kempo-backend
    env: node
    region: frankfurt
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: ENCRYPTION_SALT
        generateValue: true
      - key: CORS_ORIGIN
        value: https://kempo-frontend.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOG_LEVEL
        value: info
      - key: HOST
        value: 0.0.0.0
      - key: MAILJET_API_KEY
        value: 9763291a8f09533d6b778f61f93f7ffe
      - key: MAILJET_SECRET_KEY
        value: 8ea553808966d52807a76d2ced10ea48
    healthCheckPath: /health

  # Frontend React Service
  - type: web
    name: kempo-frontend
    env: static
    buildCommand: cd front && npm ci && npm run build
    staticPublishPath: ./front/build
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: true
      - key: REACT_APP_API_URL
        value: https://kempo-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
