name: Test Dev Workflow

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test dev workflow
        run: |
          echo "🎉 Dev workflow is working!"
          echo "Branch: ${{ github.ref }}"
