name: Test Workflow

on:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test workflow
        run: |
          echo "🎉 Workflow is working!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
